version: '3.9'

services:
  api:
    container_name: shakwa_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env.development
      - ./env/.env
    ports:
      - '3000:3000'
    restart: unless-stopped
